const words = [
    "IN MINUTEN GELIEFERT",
    "NATÜRLICHE LINDERUNG JETZT",
    "GESUNDHEIT HAT PRIORITÄT",
    "SCHNELLER ZUGANG THERAPIE",
    "SICHER DISKRET ZUVERLÄSSIG",
    "MEHR LEBENSQUALITÄT NATÜRLICH",
    "GANZHEITLICHE HEILUNG PARTNER",
  ];

  export default words;