const words = [
"IN MINUTEN GELIEFERT",
"NATÜRLICHE LINDERUNG",
"DISKRET & ZUVERLÄSSIG",
"ÄRZTLICH BEGLEITET",
"SCHNELL. SICHER. LEGAL.",
"DEIN WEG ZUR THERAPIE",
"PFLANZLICHE KRAFT",
  ];

  export default words;